[[menu.footer_left]]
name = "About"
url = "about"
weight = 1
[[menu.footer_left]]
name = "Blog"
url = "blog"
weight = 2
[[menu.footer_left]]
name = "Contact"
url = "contact"
weight = 3
[[menu.footer_middle]]
name = "Pricing"
url = "pricing"
weight = 1
[[menu.footer_middle]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 2
[[menu.footer_middle]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 3
[[menu.footer_right]]
name = "Contact"
url = "contact"
weight = 1
[[menu.footer_right]]
name = "Help Center"
url = "terms-conditions"
weight = 2
[[menu.main]]
name = "Help Center"
parent = "Support"
url = "https://help.geosync.cloud"
weight = 2
[[menu.main]]
name = "Contact"
parent = "Support"
url = "contact"
weight = 1
[[menu.main]]
name = "About"
parent = "Company"
url = "about"
weight = 1
[[menu.main]]
name = "Solutions"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Support"
url = "faq"
weight = 4
[params]
apiURL = "https://geosync.cloud"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap@5.1.3/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/brands.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/solid.min.css"
[[params.plugins.js]]
link = "https://unpkg.com/bootstrap@5.1.3/dist/js/bootstrap.min.js"
[[params.plugins.js]]
link = "https://unpkg.com/uhtml@2.8.0/min.js"
[[params.plugins.js]]
link = "https://js.stripe.com/v3/"
[[params.plugins.js]]
link = "https://player.vimeo.com/api/player.js"
[params.variables]
black = "#000"
body_color = "#fff"
border_color = "#ECECEC"
icon_font = "Font Awesome 5 Free"
light = "#EDF6F5"
primary_color = "#00AB5F"
primary_font = "Lato:wght@400"
primary_font_type = "sans-serif"
text_color = "#777"
text_color_dark = "#222"
white = "#fff"
