# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.
[params]
apiURL = "https://geosync.cloud"

######################### site variables ##############################
# customize your color and font from here.
[params.variables]
primary_color = "#00AB5F"
text_color = "#777"
text_color_dark = "#222"
body_color = "#fff"
border_color = "#ECECEC"
black = "#000"
white = "#fff"
light = "#EDF6F5"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "Lato:wght@400"
primary_font_type = "sans-serif" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"


############################# Menus ##############################
[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about"
  weight = 2

  [[menu.main]]
  name = "Blog"
  url = "blog"
  weight = 3

  [[menu.main]]
  name = "Pricing"
  url = "pricing"
  weight = 4

  [[menu.main]]
  name = "Contact"
  url = "contact"
  weight = 5

  [[menu.main]]
  name = "Support"
  url = "faq"
  weight = 6

  [[menu.main]]
  name = "Account"
  url = "account"
  weight = 5
  parent = "Support"

  [[menu.main]]
  name = "Help Center"
  url = "https://help.geosync.cloud"
  weight = 7
  parent = "Support"

  [[menu.main]]
  name = "FAQ"
  url = "faq"
  weight = 8
  parent = "Support"

  # footer menu left
  [[menu.footer_left]]
  name = "About"
  url = "about"

  [[menu.footer_left]]
  name = "Blog"
  url = "blog"

  [[menu.footer_left]]
  name = "Contact"
  url = "contact"

  # footer menu middle
  [[menu.footer_middle]]
  name = "Pricing"
  url = "pricing"

  [[menu.footer_middle]]
  name = "Privacy Policy"
  url = "privacy-policy"

  [[menu.footer_middle]]
  name = "Terms & Conditions"
  url = "terms-conditions"

  # footer menu right
  [[menu.footer_right]]
  name = "Account"
  url = "account"

  [[menu.footer_right]]
  name = "Help Center"
  url = "terms-conditions"

  [[menu.footer_right]]
  name = "FAQ"
  url = "faq"


############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap@5.1.3/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/brands.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/solid.min.css"


# JS Plugins
[[params.plugins.js]]
link = "https://unpkg.com/bootstrap@5.1.3/dist/js/bootstrap.min.js"
[[params.plugins.js]]
link = "https://unpkg.com/uhtml@2.8.0/min.js"
[[params.plugins.js]]
link = "https://js.stripe.com/v3/"
